include:
  - project: 'noah-energy/noah-pipelines-templates'
    file:    'variables.yml'

stages:
- setup

.connect-to-cluster:
  image: 
    name: registry.gitlab.com/noah-energy/swiss-army-knife-image/swiss-knife:v1.1.0
  variables:
    AWS_REGION: eu-west-1
    CLUSTER_NAME: eks-dev-env
    AWS_PROFILE: $TF_USER_DEV_ENV
  before_script:
    - aws sts get-caller-identity
    - aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME

.install-aws-load-balancer-controller:
  stage: setup
  extends: .connect-to-cluster 
  script: 
    - helm upgrade --install aws-load-balancer-controller ./charts/aws-load-balancer-controller -n kube-system 

install-aws-load-balancer-controller:development-cluster:
  extends: .install-aws-load-balancer-controller
  variables:
    AWS_REGION: eu-west-1
    CLUSTER_NAME: eks-dev-env
    AWS_PROFILE: $TF_USER_DEV_ENV
  rules: 
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - "./charts/aws-load-balancer-controller/*"

install-aws-load-balancer-controller:production-cluster:
  extends: .install-aws-load-balancer-controller
  variables:
    AWS_REGION: eu-west-1
    CLUSTER_NAME: eks-prod-env
    AWS_PROFILE: $TF_USER_PROD_ENV
  rules: 
    - if: '$CI_COMMIT_BRANCH == "production"'
      changes:
        - "./charts/aws-load-balancer-controller/*"

.install-traefik:
  stage: setup
  extends: .connect-to-cluster 
  script: 
    - helm upgrade --install traefik ./charts/traefik -n traefik --create-namespace

install-traefik:development-cluster:
  extends: .install-traefik
  needs: ["install-aws-load-balancer-controller:development-cluster"]
  variables:
    AWS_REGION: eu-west-1
    CLUSTER_NAME: eks-dev-env
    AWS_PROFILE: $TF_USER_DEV_ENV
  rules: 
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - "./charts/traefik/*"


install-traefik:production-cluster:
  extends: .install-traefik
  needs: ["install-aws-load-balancer-controller:production-cluster"]
  variables:
    AWS_REGION: eu-west-1
    CLUSTER_NAME: eks-prod-env
    AWS_PROFILE: $TF_USER_PROD_ENV
  rules: 
    - if: '$CI_COMMIT_BRANCH == "production"'
      changes:
        - "./charts/traefik/*"
