ingress:
  annotations:
    alb.ingress.kubernetes.io/tags: Environment=prod
  clusterName: eks-prod-env
  hostnames:
    - api.noahdev.org
    - noahdev.org
    - monitoring.noahdev.org
    - prod-cluster.noahdev.org
