ingress:
  annotations:
    alb.ingress.kubernetes.io/tags: Environment=dev
  clusterName: eks-dev-env
  hostnames:
    - dev-monitoring.noahdev.org
    - dev-cluster.noahdev.org
    - whoami.noahdev.org

whoami:
  enabled: true
traefik:
  deployment:
    replicas: 1
