ingress:
  annotations:
    alb.ingress.kubernetes.io/tags: Environment=prod
  clusterName: eks-prod-env
  hostnames:
    - api.noahdev.org
    - dev.api.noahdev.org
    - staging.api.noahdev.org
    - monitoring.noahdev.org
    - prod-cluster.noahdev.org

traefik:
  deployment:
    replicas: 3
