ingress:
  annotations:
    alb.ingress.kubernetes.io/tags: Environment=dev
  clusterName: eks-dev-env
  hostnames:
    - dev.api.noahdev.org
    - staging.api.noahdev.org
    - dev-monitoring.noahdev.org
    - dev-cluster.noahdev.org

