{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-ingress-{{ .Values.ingress.clusterName }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    alb.ingress.kubernetes.io/load-balancer-name: alb-ingress-{{ .Values.ingress.clusterName }}
    alb.ingress.kubernetes.io/certificate-arn: {{ join ", " .Values.ingress.certificateArns }}
    external-dns.alpha.kubernetes.io/hostname: {{ join ", " .Values.ingress.hostnames }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # name: {{ template "traefik.name" . }}
                name: traefik
                port:
                  number: {{ .Values.traefik.ports.web.exposedPort }} 
{{- end }}
