grafana:
  admin:
    user: grafana-dev-env-noah
    password: Marcotesting123
  datasources:
    secretName: prometheus-datasource
  assumeRoleArn: arn:aws:iam::848481299679:role/grafanaRoledevEnv
  dashboardsProvider:
    configMapName: default