ingressRoute:
  rule: "Host(`monitoring.noah.energy`) || Host(`monitoring.noahdev.org`)"
grafana:
  datasources:
    secretName: prometheus-datasource
  dashboardsProvider:
    configMapName: default
  grafanaRole: arn:aws:iam::848481299679:role/grafanaRoledprodEnv
