ingressRoute:
  rule: "Host(`dev-monitoring.noah.energy`) || Host(`dev-monitoring.noahdev.org`)"
grafana:
  datasources:
    secretName: prometheus-datasource
  dashboardsProvider:
    configMapName: default
  grafanaRole: arn:aws:iam::848481299679:role/grafanaRoleddevEnv
  
