apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.grafana.datasources.secretName }}
  namespace: monitoring
type: Opaque
stringData:
  datasources.yml: |-
{{ tpl (.Files.Get "datasources/prometheus.yaml") . | indent 4 }}
